# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard/dashboard_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dashboard.custom_widgets import PyQtGraphWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.targetTextLine = QtWidgets.QLineEdit(self.centralwidget)
        self.targetTextLine.setObjectName("targetTextLine")
        self.verticalLayout.addWidget(self.targetTextLine)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.predictionTextLine = QtWidgets.QLineEdit(self.centralwidget)
        self.predictionTextLine.setObjectName("predictionTextLine")
        self.verticalLayout.addWidget(self.predictionTextLine)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 2, 1)
        self.rawAudioView = PyQtGraphWidget()
        self.rawAudioView.setObjectName("rawAudioView")
        self.gridLayout.addWidget(self.rawAudioView, 1, 0, 1, 1)
        self.accuracyView = PyQtGraphWidget()
        self.accuracyView.setObjectName("accuracyView")
        self.gridLayout.addWidget(self.accuracyView, 1, 1, 1, 1)
        self.timeConsumingAudi = PyQtGraphWidget()
        self.timeConsumingAudi.setObjectName("timeConsumingAudi")
        self.gridLayout.addWidget(self.timeConsumingAudi, 1, 2, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 2, 0, 1, 4)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_5.setText(_translate("MainWindow", "Chunk"))
        self.lineEdit_6.setText(_translate("MainWindow", "Accuracy"))
        self.lineEdit_7.setText(_translate("MainWindow", "Time consuming"))
        self.lineEdit.setText(_translate("MainWindow", "Target"))
        self.lineEdit_3.setText(_translate("MainWindow", "Prediction"))
        self.startButton.setText(_translate("MainWindow", "Recording"))
